name: Node CI - Frontend

on: [push]

jobs:
  integrate:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cd frontend
        npm ci
        npm run test:unit
      env:
        CI: true
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: dist
  build:
    needs: [integrate]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
